- project:
    check:
      jobs:
        - opendev-buildset-registry
        - nebulous-component-template-helm-lint
        - nebulous-component-template-build-container-images
        - nebulous-component-template-hadolint
        - nebulous-component-template-apply-helm-charts
        - nox-linters
    gate:
      jobs:
        - opendev-buildset-registry
        - nebulous-component-template-helm-lint
        - nebulous-component-template-upload-container-images
        - nebulous-component-template-hadolint
        - nebulous-component-template-apply-helm-charts
        - nox-linters
    promote:
      jobs:
        - nebulous-component-template-promote-container-images
